services:
  - type: web
    name: shop-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JDBC_DATABASE_URL
        fromDatabase:
          name: shop-postgres
          property: connectionString
      - key: JDBC_DATABASE_USER
        fromDatabase:
          name: shop-postgres
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: shop-postgres
          property: password
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: shop-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
  - type: worker
    name: shop-worker
    runtime: docker
    dockerfilePath: ./worker.Dockerfile
    envVars:
      - key: RABBITMQ_HOST
        value: rabbitmq
      - key: RABBITMQ_PORT
        value: 5672
  - type: pserv
    name: shop-postgres
    plan: free
  - type: keyvalue
    name: shop-redis
    plan: free
